### ISSUE TITLE
Add material design theme for vaadin-text-field

### ISSUE THREAD

**Issue by Saulis** [vaadin/vaadin-themable-mixin#1]
~~Extract the current material theme demo from the text-field repository into this repo.~~

- Place a global settings file for CSS values for the theme properties into `vaadin-themes` for material theme.
- Add a separate file that will import all the required modules

```
<link rel="import" href="vaadin-themes/material.html">
<link rel="import" href="vaadin-button/vaadin-button.html">
```

Have CSS properties (with fallback values) to customize:
- colors
- font

**Comment by jouni** [comment]
## Element theme modules

> It seems that placing the style modules in the elements own repository is safest, because that will make sure that the element DOM structure is always in sync with the theme. Is there something why this would be a bad idea?

No strong objections to having them in the element repos instead. I have just had this feeling that a theme is something more generic than our elements, a design system, that could be more generally applicable, for example reusing the button and overlay styles in custom parts of your app.

So, with our planned theming solution, I could do this in the theme:

```html
<dom-module id="button-theme" theme-for="vaadin-button">
  <template>
    <style>
      :host(vaadin-button),
      [part~=themed-button] {
        /* Styles for a button */
      }
    </style>
  </template>
</dom-module>

<dom-module id="overlay-theme" theme-for="vaadin-overlay">
  <template>
    <style>
      :host(vaadin-overlay),
      [part~=themed-overlay] {
        /* Styles for a button */
      }
    </style>
  </template>
</dom-module>
```

Then I could just apply the correct `part` attributes in my own custom elements and get the same theme applied.

```html
<my-app-view>
  # shadow template
    <style include="button-theme"></style>
    <style include="overlay-theme"></style>

    <button part="themed-button">I look like a vaadin-button</button>
    <div part="themed-overlay">I look like a any vaadin element overlay</div>
</my-app-view>
```

Another reason is versioning. It would make more sense to me to version the theme as a complete whole, not as a part of the element itself. If there is a bigger design change in the theme that affects multiple elements, we would have to release a new version of each element if the themes are part of the element repos.

It seems more logical to me to have that as one logical version update for the theme instead, and if any element happens to require some updates because of the design change, then we would release a new compatible version of that element. Having design changes that require changes to the element’s themselves feels less common/frequent than design changes that span across multiple element themes.

## Global theme

> We would still need to have a global theme file which would at least set values to the theme CSS properties – this could be placed for example in `vaadin-core-elements` or `vaadin-themes` repository, where we could also have a demo page displaying all the themed components.

The core elements bundle feels like the wrong place. That means that each individual element would need to depend on the bundle to have access to the the global stuff. Or, then we will have to have the default values for any global custom properties set explicitly in each individual element.

Having a demo that shows all themed elements together is probably something we want to have.

**Comment by jouni** [comment]
After gathering some opinions from the designers at Vaadin, the majority considered it a more natural option to bundle the themes together in a separate repo instead of having them in the individual element repos.

As we didn’t really find a consensus among the dev team that would counter the designers’ preference, and have already taken initial steps towards having all element themes in one repo (vaadin-themes), we will go with that decision now.

**Comment by jouni** [comment]
I’m also closing this issue, as it is in the wrong repo now. I’ll open a new one with updated specs/requirements in the vaadin-themes repo.
