### ISSUE TITLE
Current way of styling doesn't work with `polymer build`

### ISSUE THREAD

**Issue by limonte** [vaadin/vaadin-themable-mixin#36]
`vaadin-themable-mixin` is currently incompatible with `polymer build`

Here's the small demo to reproduce: https://github.com/limonte/vaadin-text-field-theming-issue/tree/master

### Steps to reroduce

- clone the repo
- `polymer build`
- open `build/es6-bundled/index.html` in browser

### Expected

![image](https://user-images.githubusercontent.com/6059356/48474288-ea1abe80-e802-11e8-93bc-4c9d20203a04.png)

### Actual

Unstyled text field.

**Comment by jouni** [comment]
That’s odd. I’m also using `polymer build` for jelements.netlify.com, and you can see a styled vaadin-text-field at the end of https://jelements.netlify.com/field

Maybe it’s broken only if you use ES6? I’m using the `es5-bundled` preset: https://github.com/jouni/j-elements/blob/master/site/polymer.json#L24

**Comment by samiheikki** [comment]
Sounds like to be related with https://github.com/vaadin/vaadin-lumo-styles/issues/6

**Comment by samiheikki** [comment]
I think the common practice with `polymer build` is to create an app shell (element) for your app and to have all the elements inside that. And configure the correct app shell in your `polymer.json`

So when modifying the app structure it would look like this: https://github.com/samiheikki/vaadin-text-field-theming-issue/commit/8582ca47f0043c97150042598ed5f3fd9bcef7ec

In that example the styling works correctly with `polymer build`.

**Comment by limonte** [comment]
> I think the common practice with polymer build is to create an app shell (element) for your app and to have all the elements inside that.

That practice is common in Polymer community indeed, but that doesn't mean users are obligated to use it, right? Also, that common practice is very questionable as describe in this nice article: https://equinsuocha.io/blog/web-components-the-right-way (see "The Wrong Way" section).

**Comment by samiheikki** [comment]
People outside of Polymer community would probably not use `polymer build` to build their app and thus not having this issue.

**Comment by cwenzelg** [comment]
Wenn i'm not really experienced enough for a qualified suggestion but as i started with issue with the help of limonte, i would like to share our usecase: 

We have a webpage with a complex backend but also with a wide range of "dynamic" landing pages with individual urls etc. similar to a CMS. We use polymer for quite a while as we love the web component reusability and we are working with templates that allow a full page load (with the "app-shell") or a partial html file with just the content and maybe some additional fragment. the idea started with this superchared inspiration: https://www.youtube.com/watch?v=8LM4p7l9YMY&t=83s . We use the polymer  build process because we use the 3 different bundles and our base template injects the correct app shell depending on the detected browser versions for the first full page load. Everything in one app Shell is just too big to load in a acceptable loading time.

As i get it we could try to recreate the bunding with webpack but i got so many "element got already declared" errors, that we keep the polymer build process for now. Currently, we wrap the vaadin elements into a wrapper element passing the values we need, but it isn't really working with grids right now and we needed an iron-form registration to work with forms.

If the vaadin elements are correct and polymer build is the problem maybe you could describe this issue to the polymer team. i still don't understand the technical implications of this issue right now to suggest a change myself.

**Comment by web-padawan** [comment]
Note: happens for both ES6 and ES5 builds.

### ES6 build (`"compile": "es2015"`)

```
  customElements.define(TextFieldElement.is, TextFieldElement);
  var vaadinTextField = {
    TextFieldElement: TextFieldElement
  };
  _exports.$vaadinTextField = vaadinTextField;
  const $_documentContainer$7 = html`<dom-module id="lumo-text-field" theme-for="vaadin-text-field">
```

### ES5 build (`"compile": "es5"`)

```
  _exports.TextFieldElement = TextFieldElement;
  customElements.define(TextFieldElement.is, TextFieldElement);
  var vaadinTextField = {
    TextFieldElement: TextFieldElement
  };
  _exports.$vaadinTextField = vaadinTextField;
  var $_documentContainer$7 = html(_templateObject2_3fdd59e0f7c111e880e6ef496fc9ddd9());
  document.head.appendChild($_documentContainer$7.content);
```

**Comment by web-padawan** [comment]
The actual repo link: https://github.com/web-padawan/vaadin-text-field-theming-issue

**Comment by web-padawan** [comment]
We no longer recommend `polymer build`, and while this issue is still valid, there is nothing we can really do about it.
Vaadin 14+ is using `webpack` and for frontend projects we recommend the [Rollup preset](https://open-wc.org/docs/building/rollup/) by Open Web Components.

Closing this as won't fix.
