### ISSUE TITLE
Ensure the order of theme modules when including styles

### ISSUE THREAD

**Issue by web-padawan** [vaadin/vaadin-themable-mixin#38]
Currently, we don't check in which order themes are being included. This can result in the unexpected breaking changes caused by the internal CSS refactoring like vaadin/vaadin-text-field#257

Original report: https://vaadin.com/forum/thread/17418133/theme-issue-for-vaadin-12

### Before (vaadin-text-field 2.0.x)

Users styles come first:

![screen shot 2018-12-03 at 10 56 12](https://user-images.githubusercontent.com/10589913/49365047-6c095380-f6ee-11e8-9e01-656365578467.png)

### After (vaadin-text-field >2.1.3)

We are overriding the styles set by user:

![screen shot 2018-12-03 at 10 55 09](https://user-images.githubusercontent.com/10589913/49365099-92c78a00-f6ee-11e8-8413-f89e747d1d1c.png)

One way could be iterating over theme modules and checking the prefix. However, that would mean the "whitelist"  for Vaadin themes, and it's very undesirable to mention Lumo, Material etc here.

Also, no one can disallow the user to actually call his own module `vaadin-my-styles` and break our assumptions. So, this is not that easy to fix now, but we should consider it for "next generation".

**Comment by lkraav** [comment]
OK, and the intermediate workaround is "use better CSS specificity"?

**Comment by web-padawan** [comment]
Yes, for now the CSS specificity is the way to go, and in general it is the only 100% solution (as some tools, like bundlers, might change the order of scripts and files, especially for Polymer 3).

**Comment by Legioth** [comment]
Instead of hardcoding specific rules for `vaadin-` named modules, I'd suggest assigning priorities to the modules: https://github.com/vaadin/vaadin-themable-mixin/issues/28#issuecomment-445474889. 

To help the change take effect immediately when `vaadin-themable-mixin` is updated instead of having to also update all components to versions with explicit priorities, the default priority for `vaadin-` prefixed modules could still be lower than for other modules.

**Comment by AStaroverov** [comment]
How i can should reload lume theme? Before I had some style and registered is after lumo theme.
Now it doesnt work, because u add sort...

**Comment by AStaroverov** [comment]
May be u have incorrect sort? Lumo and meterial themes now includes after other themes

**Comment by web-padawan** [comment]
@AStaroverov can you provide us with an example of how do you import themes in your app?
Generally, it's better to import Lumo or Material explicitly, in case if your theme depends on it.

**Comment by tomivirkki** [comment]
After the change, the include order should be:
1. `vaadin-` -themes
2. `lumo-` and `material-` -themes (that can override `vaadin-` themes)
3. the rest of the themes (your custom themes) so that they can override everything above.

Note that if your theme id starts with `vaadin-`, it might get run over by `lumo-` and `material-` themes (in case the selectors aren't stronger). Better use id's that don't start with `vaadin-`, `lumo-` or `material-` for your custom styles.

**Comment by AStaroverov** [comment]
@tomivirkki , thx, we have themes started with `vaadin-`. sorry for my mistake

**Comment by tomivirkki** [comment]
No problem. It's more our mistake, we should document this better now that the include order is fixed. Added an issue for it https://github.com/vaadin/vaadin-themable-mixin/issues/45
